### ISSUE TITLE
The output should be ASCII characters not numbers

### ISSUE THREAD

**Issue by TheLizzard** [Thive-N/.BF-Compiler#1]
On line 97 it says:
                self.Output.insert(END,"OUT: "+str(self.Cells[self.Pointer_C])+"\n")
if you make it into:
                self.Output.insert(END,"OUT: "+str(char(self.Cells[self.Pointer_C]))+"\n")
it will show characters instead of numbers. It will work with the simple hello world program from Wikipedia.

**Comment by Thive-N** [comment]
I have it outputting numbers right now so its easier to identify problems.
once I've finished with all the logic side of things I'll make sure I add that in.
