### ISSUE TITLE
Clear output button not working

### ISSUE THREAD

**Issue by TheLizzard** [Thive-N/.BF-Compiler#2]
The clear output button isn't working.
If you change *line 26* to:
`self.ClearOutput=Button(self.frame,text="Clear Output", command=self.clear_output).grid(column = 1 , row = 1)`

and add a new method:
`def clear_output(self): self.Output.delete("0.0", "end")`

then the button will work.

**Comment by Thive-N** [comment]
ill add that in right now thanks for pointing that out
